on:
  push:
    branches: [staging]

jobs:
  print-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging]
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Railway
        run: bun i -g @railway/cli
      - name: Deploy
        run: |
          echo "NODE_ENV=${{ matrix.environment }}"
          echo "GITHUB_TOKEN=${{ env.GITHUB_TOKEN }}"
          echo "REPOSITORY_SECRET=${{ env.REPOSITORY_SECRET }}"
          echo "REPOSITORY_VARIABLE=${{ env.REPOSITORY_VARIABLE }}"
          echo "ENVIRONMENT_SECRET=${{ env.ENVIRONMENT_SECRET }}"
          echo "ENVIRONMENT_VARIABLE=${{ env.ENVIRONMENT_VARIABLE }}"
          echo "RAILWAY_TOKEN=${{ env.RAILWAY_TOKEN }}"
          echo ${{ github.env }} > .env
          railway up -e ${{ env.NODE_ENV }}
        env:
          NODE_ENV: ${{ matrix.environment }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_SECRET: ${{ secrets.REPOSITORY_SECRET }}
          REPOSITORY_VARIABLE: ${{ env.REPOSITORY_VARIABLE }}
          ENVIRONMENT_SECRET: ${{ github.env.ENVIRONMENT_SECRET }}
          ENVIRONMENT_VARIABLE: ${{ github.env.ENVIRONMENT_VARIABLE }}
          RAILWAY_TOKEN: ${{ env.RAILWAY_TOKEN }}
        #   RAILWAY_TOKEN: ${{ github.env.secrets.RAILWAY_TOKEN}}
        #   RAILWAY_TOKEN: ${{ github.env.RAILWAY_TOKEN }}
        #   RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
