on:
  push:
    branches: [staging]

jobs:
  print-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging]
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Railway
        run: bun i -g @railway/cli
      - name: Deploy
        run: railway up -e ${{ matrix.environment }}
        env:
          github_env: ${{ matrix.environment }}
          REPOSITORY_SECRET: ${{ secrets.REPOSITORY_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RAILWAY_TOKEN: ${{ github.env.secrets.RAILWAY_TOKEN}}
        #   RAILWAY_TOKEN: ${{   .RAILWAY_TOKEN }}
        #   RAILWAY_TOKEN: ${{ github.env.RAILWAY_TOKEN }}
        #   RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        #   REPOSITORY_VARIABLE: ${{ env.REPOSITORY_VARIABLE }}
        #   ENVIRONMENT_SECRET: ${{ github.env.ENVIRONMENT_SECRET }}
        #   ENVIRONMENT_VARIABLE: ${{ github.env.ENVIRONMENT_VARIABLE }}
