on:
  push:
    branches: [main, staging]

jobs:
  print-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging, production]
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Railway
        run: bun i -g @railway/cli
      - name: Deploy
        run: railway up -e ${{ matrix.environment }}
        env:
          REPOSITORY_SECRET: ${{ secrets.REPOSITORY_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_VARIABLE: ${{ env.REPOSITORY_VARIABLE }}
          ENVIRONMENT_SECRET: ${{ github.env.ENVIRONMENT_SECRET }}
          ENVIRONMENT_VARIABLE: ${{ github.env.ENVIRONMENT_VARIABLE }}
          RAILWAY_TOKEN: ${{ github.env.RAILWAY_TOKEN }}
