on:
  push:
    branches: [staging]

jobs:
  print-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: staging
            token: RAILWAY_TOKEN
            variable: ENVIRONMENT_VARIABLE
            secret: ENVIRONMENT_SECRET
          - environment: production
            token: RAILWAY_TOKEN
            variable: ENVIRONMENT_VARIABLE
            secret: ENVIRONMENT_SECRET
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Deploy
        run: |
          npm i -g @railway/cli
          echo "NODE_ENV=${{ env.NODE_ENV }}"
          echo "GITHUB_TOKEN=${{ env.GITHUB_TOKEN }}"
          echo "REPOSITORY_VARIABLE=${{ env.REPOSITORY_VARIABLE }}"
          echo "REPOSITORY_SECRET=${{ env.REPOSITORY_SECRET }}"
          echo "ENVIRONMENT_VARIABLE=${{ env.ENVIRONMENT_VARIABLE }}"
          echo "ENVIRONMENT_SECRET=${{ env.ENVIRONMENT_SECRET }}"
          echo "RAILWAY_TOKEN=${{ env.RAILWAY_TOKEN }}"
          pwd
          ls -al
          cat .env
          railway up -e ${{ env.NODE_ENV }}

        env:
          NODE_ENV: ${{ matrix.environment }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_VARIABLE: ${{ vars.REPOSITORY_VARIABLE }}
          REPOSITORY_SECRET: ${{ secrets.REPOSITORY_SECRET }}
          ENVIRONMENT_VARIABLE: ${{ vars[matrix.variable] }}
          ENVIRONMENT_SECRET: ${{ secrets[matrix.secret] }}
          RAILWAY_TOKEN: ${{ secrets[matrix.token] }}
