on:
  push:
    branches: [main, staging]

jobs:
  show-secrets:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging, production]
    steps:
      - name: Show secrets
        run: |
          echo "Environment: ${{ matrix.environment }}"
          echo ${{ env.REPOSITORY_SECRET }}
          echo ${{ env.REPOSITORY_VARIABLE }}
          echo ${{ env.ENVIRONMENT_SECRET }}
          echo ${{ env.ENVIRONMENT_VARIABLE }}
        env:
          REPOSITORY_SECRET: ${{ secrets.REPOSITORY_SECRET }}
          REPOSITORY_VARIABLE: ${{ env.REPOSITORY_VARIABLE }}
          ENVIRONMENT_SECRET: ${{ github.env.ENVIRONMENT_SECRET }}
          ENVIRONMENT_VARIABLE: ${{ github.env.ENVIRONMENT_VARIABLE }}
